apiVersion: apps/v1
kind: Deployment
metadata:
  name: irmsdeployment
  labels:
    app: irmsdeployment
  namespace: namespace-workflow-1703351939993
spec:
  replicas: 1
  selector:
    matchLabels:
      app: irmsdeployment
  template:
    metadata:
      labels:
        app: irmsdeployment
    spec:
      containers:
        - name: irmsdeployment
          image: acrworkflow1703351939993.azurecr.io/image-workflow-1703351939993:latest
          ports:
            - containerPort: 8000