apiVersion: v1
kind: Service
metadata:
  name: irmsdeployment
  namespace: namespace-workflow-1703351939993
spec:
  type: LoadBalancer
  selector:
    app: irmsdeployment
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000