apiVersion: v1
kind: Service
metadata:
  name: irms_test_workflowv2
  namespace: namespace-workflow-1703351066105
spec:
  type: LoadBalancer
  selector:
    app: irms_test_workflowv2
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000